language: node_js
node_js:
- "6.10"
cache:
  directories:
    - node_modules
deploy:
  - provider: script
    script: bin/deploy.sh
    skip_cleanup: true
    on:
      branch: master
cache:
  directories:
    - node_modules
