sudo: required 
language: node_js
node_js:
- "8.9.4"
env:
  global:
    - COVERALLS_SERVICE_NAME=travis-pro
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
before_install:
  - openssl aes-256-cbc -K $encrypted_b1e88cd19300_key -iv $encrypted_b1e88cd19300_iv -in meetupnow-google.json.enc -out meetupnow-google.json -d
install:
  - pip install --user awscli
  - yarn install
before_script:
  - psql -c 'create database meetup_now_test;' -U postgres
  - psql -U postgres -d meetup_now_test -c "create extension postgis"
  - yarn migrate:test
script:
  - yarn test
after_success:
  - yarn coveralls < coverage/lcov.info
deploy:
  - provider: script
    script: bin/deploy.sh now-api $TRAVIS_BUILD_NUMBER-`git rev-parse --short HEAD` now-api-prod now-api-jobs now-api-staging
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bin/deploy.sh now-api $TRAVIS_BUILD_NUMBER-`git rev-parse --short HEAD` now-api-staging
    skip_cleanup: true
    on:
      branch: staging
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
