language: node_js
node_js:
- "6.10"
cache:
  directories:
    - node_modules
deploy:
  - provider: script
    script:
      - npm install -g serverless
      - sls deploy
    skip_cleanup: true
    on:
      branch: master
cache:
  directories:
    - node_modules
