sudo: required 
language: node_js
node_js:
- "8.9.4"
env:
  global:
    - COVERALLS_SERVICE_NAME=travis-pro
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_b1e88cd19300_key -iv $encrypted_b1e88cd19300_iv -in meetupnow-google.json.enc -out meetupnow-google.json -d
install:
  - pip install --user awscli
  - yarn install
script:
  - yarn test
after_success:
  - yarn coveralls < coverage/lcov.info
deploy:
  - provider: script
    script: bin/deploy.sh now-api now-api-prod $TRAVIS_BUILD_NUMBER-`git rev-parse --short HEAD`
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bin/deploy.sh now-api now-api-next $TRAVIS_BUILD_NUMBER-`git rev-parse --short HEAD`-NEXT
    skip_cleanup: true
    on:
      branch: next
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
